/// Flutter icons AppIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcon
///      fonts:
///       - asset: fonts/AppIcon.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIcon {
  AppIcon._();

  static const _kFontFam = 'AppIcon';
  static const String? _kFontPkg = null;

  static const IconData stackoverflow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_city = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData axe_swing = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_sword = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battered_axe = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bleeding_eye = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottle_vapors = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowie_knife = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockwork = IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clover = IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cracked_helm = IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_axes = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_pistols = IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData defibrillate = IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragonfly = IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_shield = IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groundbreaker = IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hydra = IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData incense = IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData metal_gate = IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror = IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData regeneration = IconData(0xea7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_unfurled = IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sheriff = IconData(0xea95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supersonic_arrow = IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wyvern = IconData(0xeaeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zebra_shield = IconData(0xeaed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xf002, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xf21e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_alt = IconData(0xf2ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open = IconData(0xf518, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xf5a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xf64f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost = IconData(0xf6e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
